platform:
  - 'platform/*'
services/platform/dev:
  - 'services/platform/dev/*'
services/api-front/dev:
  - 'services/api-front/dev/*'
services/ms-web/dev:
  - 'services/ms-web/dev/*'
services/ms-user/dev:
  - 'services/ms-user/dev/*'
