platform:
  AWS_ACCOUNT_ID: AWS_ACCOUNT_ID_PLATFORM
services/_common/dev:
  AWS_ACCOUNT_ID: AWS_ACCOUNT_ID_DEV
services/api-front/dev:
  AWS_ACCOUNT_ID: AWS_ACCOUNT_ID_DEV
services/ms-web/dev:
  AWS_ACCOUNT_ID: AWS_ACCOUNT_ID_DEV
services/ms-user/dev:
  AWS_ACCOUNT_ID: AWS_ACCOUNT_ID_DEV
