platform:
  - 'platform/*'
services/_common/dev:
  - 'services/_common/dev/*'
services/api-front/dev:
  - 'services/api-front/dev/*'
services/ms-web/dev:
  - 'services/ms-web/dev/*'
services/ms-user/dev:
  - 'services/ms-user/dev/*'
