name: terraform modules
on:
  pull_request:
env:
  AWS_REGION : "ap-northeast-1"
permissions:
  id-token: write
  contents: read
jobs:
  determine-workdir:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      workdirs: ${{ steps.filter.outputs.workdirs }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: .github/path-filter-for-modules.yml

      - name: filter
        id: filter
        run: |
          WORKDIRS=$(echo '${{ toJSON(steps.changes.outputs) }}' | jq '. | to_entries[] | select(.value == "true") | .key') 
          echo "workdirs=$(echo $WORKDIRS | jq -sc '.')" >> $GITHUB_OUTPUT

  generate-docs:
    runs-on: ubuntu-latest
    needs: determine-workdir
    if: needs.determine-workdir.outputs.workdirs != '[]'
    strategy:
      fail-fast: false
      matrix:
        workdir: ${{ fromJSON(needs.determine-workdir.outputs.workdirs) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@cf462c5da36feb66051cf0a6f1124594ed9adc7c # v0.20.0
        with:
            working-dir: .
            output-file: README.md
            output-method: inject
            git-push: "true"
  status-check:
    needs: [determine-workdir, generate-docs]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1